# Generated by Django 6.0.3 on 2026-04-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_equipo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='solicitante_externo',
            field=models.CharField(blank=True, help_text='Nombre del solicitante externo (entrenador, etc.)', max_length=150, null=True),
        ),
    ]
