# Generated by Django 6.0.3 on 2026-04-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_prestamo_solicitante_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre el préstamo', null=True),
        ),
    ]
